/** mobile 全量字典：zh 为权威键集合，en 类型强制同键。 */

export const zh = {
  // 骨架自用（MineView 语言切换行）
  'common.language': '界面语言',
  'common.languageHint': '移动站界面语言（本机浏览器保存）',
  'common.languageZh': '中文',
  'common.languageEn': 'English',

  // 通用（跨文件复用）
  'common.appTitle': 'Volund 远程',
  'common.copy': '复制',
  'common.copied': '已复制',
  'common.cancel': '取消',
  'common.delete': '删除',
  'common.retry': '重试',
  'common.send': '发送',
  'common.failed': '失败',
  'common.running': '运行中',
  'common.loading': '加载中…',
  'common.save': '保存',

  // chat.ts
  'chat.offlineNotice': '本机离线：桌面端隧道已断开，恢复后自动重连',
  'chat.stalledNotice': '长时间未收到新事件，本轮可能已中断；可点「中断」结束',
  'chat.truncated': '…（已截断）',
  'chat.groupDone': '{n} 个完成',
  'chat.groupRunning': '{n} 个运行中',

  // ChatView.tsx
  'chat.thinkingLabel': '思考过程',
  'chat.toolCallCount': '{count} 次调用',
  'chat.imageLoading': '加载 {name}',
  'chat.loadingConversation': '对话加载中…',
  'chat.emptyTitle': '这里静悄悄的…',
  'chat.emptySubtitle': '发条消息，唤醒你的助手 ✨',
  'chat.imageBusyNotice': '当前回合进行中：带图片的消息请等回合结束后再发送',
  'chat.runningTool': '正在运行 {name}…',
  'chat.thinkingInitial': '正在思考…',
  'chat.thinkingOngoing': '思考中…',
  'chat.subagent': '子代理',
  'chat.elapsedSuffix': '（{seconds}s{tokens}）',
  'chat.interrupted': '已中断本次回复',
  'chat.removeImage': '移除 {name}',
  'chat.addImage': '添加图片',
  'chat.placeholder': '发消息…',
  'chat.connecting': '连接中…',
  'chat.interrupt': '中断',
  'chat.sendQueue': '发送队列',
  'chat.dragReorder': '拖动排序：{name}',
  'chat.removeFromQueue': '移出队列',
  'chat.noSessionEmpty': '没有进行中的会话',
  'chat.goSessions': '去选择会话',

  // PermissionStack.tsx
  'perm.title': '权限请求',
  'perm.autoDenying': '自动拒绝中…',
  'perm.autoDenyIn': '{seconds}s 后自动拒绝',
  'perm.queueTabs': '待审批队列',
  'perm.details': '详情',
  'perm.denyOnlyHint': '该请求细节无法安全展示，仅可拒绝（fail closed）',

  // AskStack.tsx
  'ask.title': '提问',
  'ask.autoClosing': '自动关闭中…',
  'ask.autoCloseIn': '{seconds}s 后自动关闭',
  'ask.queueTabs': '待决提问队列',
  'ask.freetextPlaceholder': '自定义回答（不选选项）',
  'ask.freetextLabel': '自定义回答',
  'ask.freetextSend': '发送自定义回答',
  'ask.skip': '跳过（不作答）',

  // page.tsx（底栏 tab / 页头 / 提示条）
  'tab.sessions': '会话',
  'tab.chat': '对话',
  'tab.tasks': '任务',
  'tab.mine': '我的',
  'page.modelPlaceholder': '模型',
  'page.permissionStaleNotice': '审批未生效：该请求已被处理或过期',
  'page.askStaleNotice': '作答未生效：该提问已被处理或过期',
  'page.errorNotice': '错误 {code}: {message}',
  'page.needSessionFirst': '请先创建会话',
  'page.sessionStartTimeout': '会话建立超时，请重试',
  'page.notPaired': '未配对',
  'page.revokedNotice': '设备已被桌面端撤销，请重新配对',
  'page.credentialsInvalidNotice': '凭证已失效或被撤销，请重新配对',

  // TasksView.tsx
  'tasks.everyMinutes': '每 {minutes} 分钟',
  'tasks.dailyAt': '每天 {at}',
  'tasks.weeklyAt': '每周 {weekdays} {at}',
  'tasks.runCompleted': '完成',
  'tasks.runMissed': '错过',
  'tasks.runSkipped': '跳过',
  'tasks.refresh': '刷新任务',
  'tasks.schedulerDisabled': '调度未启用（本机 config [tasks].enabled）；以下为缓存数据。',
  'tasks.daemonDown': 'daemon 未运行——任务不会触发。',
  'tasks.definitions': '任务定义',
  'tasks.noDefinitions': '没有任务定义',
  'tasks.enabled': '启用',
  'tasks.disabled': '停用',
  'tasks.filtering': '筛选中',
  'tasks.runsHeader': '运行记录（新→旧）',
  'tasks.noRuns': '没有运行记录',

  // SessionsView.tsx
  'sessions.current': '当前',
  'sessions.untitled': '未命名会话',
  'sessions.emptyDescription': '还没有会话，新建一个开始远程对话',
  'sessions.newChat': '新建会话',
  'sessions.newSession': '新会话',
  'sessions.deleteTitle': '删除会话',
  'sessions.deleteConfirm': '删除「{name}」？事件流与附件会一并清除，不可恢复。',
  'sessions.copyId': '复制ID',
  'sessions.copyIdPayload': '设备ID: {device}\n会话ID: {session}',
  'sessions.copyFailed': '复制失败：剪贴板不可用',
  'sessions.refreshing': '刷新中…',
  'sessions.releaseToRefresh': '释放刷新',
  'sessions.pullToRefresh': '下拉刷新',

  // MineView.tsx
  'mine.appearance': '外观',
  'mine.themeAuto': '自动',
  'mine.themeLight': '白昼',
  'mine.themeDark': '暗夜',
  'mine.gateway': '网关',
  'mine.link': '链路',
  'mine.connected': '已连接',
  'mine.reconnecting': '重连中',
  'mine.session': '会话',
  'mine.noActiveSession': '无活动会话',
  'mine.device': '设备',
  'mine.credentialExpiry': '凭证有效期至',
  'mine.credentialHint':
    '设备凭证由网关签发（默认 30 天）；如需立即失效，请在桌面「远程控制」页撤销本设备。',
  'mine.unpairTitle': '解除配对？',
  'mine.unpairDescription': '清除本机凭证并回到配对页（桌面端撤销可立即失效）',
  'mine.unpair': '解除配对',

  // SubagentsRow.tsx
  'subagents.region': 'subagent 运行',
  'subagents.header': 'Subagents · {running} 运行中 / {total} 总计',
  'subagents.completed': '已完成',
  'subagents.partial': '部分结果',
  'subagents.cancelled': '已取消',
  'subagents.interrupted': '已中断',
  'subagents.cancelling': '取消中…',

  // ChangesCard.tsx
  'changes.title': '{count} 个文件已更改',
  'changes.undo': '撤销',
  'changes.noBackup': '该路径没有本会话的备份记录',
  'changes.tooLarge': '文件过大，净效果 diff 不做全量渲染',
  'changes.created': '会话新建的文件（当前无净变化）',
  'changes.noDiff': '与备份起点无差异（可能已撤销）',
  'changes.undone': '已撤销',
  'changes.undoTitle': '撤销上一批变更',
  'changes.undoConfirm': '确认撤销',
  'changes.undoPreviewPrefix': '将撤销 ',
  'changes.undoPreviewSuffix': ' 个文件的上一批变更：',
  'changes.warnModified': '{path}: 备份后曾被外部修改，撤销可能覆盖手工改动',
  'changes.warnMissing': '{path}: 备份对象缺失，该文件将跳过',
  'changes.noUndoable': '没有可撤销的批次（no_backup）。',

  // PairView.tsx
  'pair.deviceFallback': '设备',
  'pair.subtitle': '在桌面 Web 控制台「远程控制」页生成配对码，扫码或在此输入',
  'pair.pairing': '正在配对…',
  'pair.codePlaceholder': '8 位配对码',
  'pair.pair': '配对',
  'pair.gatewayPlaceholder': '网关地址（可选）https://…',
  'pair.gatewaySaved': '网关地址已保存',
  'pair.gatewayHint': '网关：{label}（独立部署时先填网关地址）',

  // WelcomeView.tsx
  'welcome.subtitle': '远程控制你的 Volund 桌面端',
  'welcome.entering': '已连接，正在进入…',
  'welcome.connecting': '正在连接网关 {host}…',
  'welcome.skip': '暂不连接，直接进入',

  // gateway.ts
  'gateway.baseInvalid': '网关地址须以 http(s):// 开头',
  'gateway.connectFailed':
    '连不上网关：确认网关地址可达；跨源部署时网关侧须把本站 Origin 加进 GATEWAY_CORS_ORIGINS',
  'gateway.pairFailed': '配对失败（{status}）',
  'gateway.sessionExpired': '凭证已失效，请重新配对',
  'gateway.requestFailed': '网关请求失败（{status}）',
  'gateway.uploadFailed': '图片上传失败（{status}）',
  'gateway.downloadFailed': '图片下载失败（{status}）',
} as const

export type DictKey = keyof typeof zh

export const en: Record<DictKey, string> = {
  'common.language': 'Language',
  'common.languageHint': 'Mobile UI language (saved in this browser)',
  'common.languageZh': '中文',
  'common.languageEn': 'English',

  'common.appTitle': 'Volund Remote',
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.retry': 'Retry',
  'common.send': 'Send',
  'common.failed': 'Failed',
  'common.running': 'Running',
  'common.loading': 'Loading…',
  'common.save': 'Save',

  'chat.offlineNotice':
    'This device is offline: the desktop tunnel is down; it reconnects automatically',
  'chat.stalledNotice':
    'No new events for a while — this turn may have stalled; tap Interrupt to end it',
  'chat.truncated': '… (truncated)',
  'chat.groupDone': '{n} done',
  'chat.groupRunning': '{n} running',

  'chat.thinkingLabel': 'Thinking',
  'chat.toolCallCount': '{count} calls',
  'chat.imageLoading': 'Loading {name}',
  'chat.loadingConversation': 'Loading conversation…',
  'chat.emptyTitle': 'All quiet in here…',
  'chat.emptySubtitle': 'Send a message to wake up your assistant ✨',
  'chat.imageBusyNotice':
    'A turn is already running: wait for it to finish before sending messages with images',
  'chat.runningTool': 'Running {name}…',
  'chat.thinkingInitial': 'Thinking…',
  'chat.thinkingOngoing': 'Still thinking…',
  'chat.subagent': 'Subagent',
  'chat.elapsedSuffix': ' ({seconds}s{tokens})',
  'chat.interrupted': 'Interrupted this reply',
  'chat.removeImage': 'Remove {name}',
  'chat.addImage': 'Add image',
  'chat.placeholder': 'Type a message…',
  'chat.connecting': 'Connecting…',
  'chat.interrupt': 'Interrupt',
  'chat.sendQueue': 'Send queue',
  'chat.dragReorder': 'Drag to reorder: {name}',
  'chat.removeFromQueue': 'Remove from queue',
  'chat.noSessionEmpty': 'No active session',
  'chat.goSessions': 'Pick a session',

  'perm.title': 'Permission request',
  'perm.autoDenying': 'Auto-denying…',
  'perm.autoDenyIn': 'Auto-deny in {seconds}s',
  'perm.queueTabs': 'Pending approvals',
  'perm.details': 'Details',
  'perm.denyOnlyHint': 'Details cannot be shown safely; deny only (fail closed)',

  'ask.title': 'Question',
  'ask.autoClosing': 'Auto-closing…',
  'ask.autoCloseIn': 'Auto-close in {seconds}s',
  'ask.queueTabs': 'Pending questions',
  'ask.freetextPlaceholder': 'Custom answer (skip the options)',
  'ask.freetextLabel': 'Custom answer',
  'ask.freetextSend': 'Send custom answer',
  'ask.skip': 'Skip (no answer)',

  'tab.sessions': 'Sessions',
  'tab.chat': 'Chat',
  'tab.tasks': 'Tasks',
  'tab.mine': 'Mine',
  'page.modelPlaceholder': 'Model',
  'page.permissionStaleNotice':
    'Decision not applied: the request was already handled or has expired',
  'page.askStaleNotice': 'Answer not applied: the question was already handled or has expired',
  'page.errorNotice': 'Error {code}: {message}',
  'page.needSessionFirst': 'Create a session first',
  'page.sessionStartTimeout': 'Session creation timed out, please retry',
  'page.notPaired': 'Not paired',
  'page.revokedNotice': 'This device was revoked from the desktop; please pair again',
  'page.credentialsInvalidNotice': 'Credentials expired or revoked; please pair again',

  'tasks.everyMinutes': 'Every {minutes} minutes',
  'tasks.dailyAt': 'Daily at {at}',
  'tasks.weeklyAt': 'Weekly on {weekdays} at {at}',
  'tasks.runCompleted': 'Done',
  'tasks.runMissed': 'Missed',
  'tasks.runSkipped': 'Skipped',
  'tasks.refresh': 'Refresh tasks',
  'tasks.schedulerDisabled':
    'Scheduler disabled (local config [tasks].enabled); showing cached data.',
  'tasks.daemonDown': 'Daemon is not running — tasks will not fire.',
  'tasks.definitions': 'Task definitions',
  'tasks.noDefinitions': 'No task definitions',
  'tasks.enabled': 'Enabled',
  'tasks.disabled': 'Disabled',
  'tasks.filtering': 'Filtering',
  'tasks.runsHeader': 'Runs (new → old)',
  'tasks.noRuns': 'No runs',

  'sessions.current': 'Current',
  'sessions.untitled': 'Untitled session',
  'sessions.emptyDescription': 'No sessions yet — create one to start remote chats',
  'sessions.newChat': 'New chat',
  'sessions.newSession': 'New session',
  'sessions.deleteTitle': 'Delete session',
  'sessions.deleteConfirm':
    'Delete "{name}"? The event stream and attachments will be cleared too. This cannot be undone.',
  'sessions.copyId': 'Copy ID',
  'sessions.copyIdPayload': 'Device ID: {device}\nSession ID: {session}',
  'sessions.copyFailed': 'Copy failed: clipboard unavailable',
  'sessions.refreshing': 'Refreshing…',
  'sessions.releaseToRefresh': 'Release to refresh',
  'sessions.pullToRefresh': 'Pull to refresh',

  'mine.appearance': 'Appearance',
  'mine.themeAuto': 'Auto',
  'mine.themeLight': 'Light',
  'mine.themeDark': 'Dark',
  'mine.gateway': 'Gateway',
  'mine.link': 'Connection',
  'mine.connected': 'Connected',
  'mine.reconnecting': 'Reconnecting',
  'mine.session': 'Session',
  'mine.noActiveSession': 'No active session',
  'mine.device': 'Device',
  'mine.credentialExpiry': 'Credentials valid until',
  'mine.credentialHint':
    'Device credentials are issued by the gateway (30 days by default); to revoke immediately, remove this device from the desktop Remote Control page.',
  'mine.unpairTitle': 'Unpair?',
  'mine.unpairDescription':
    'Clears local credentials and returns to the pairing page (desktop revocation takes effect immediately)',
  'mine.unpair': 'Unpair',

  'subagents.region': 'Subagent runs',
  'subagents.header': 'Subagents · {running} running / {total} total',
  'subagents.completed': 'Completed',
  'subagents.partial': 'Partial',
  'subagents.cancelled': 'Cancelled',
  'subagents.interrupted': 'Interrupted',
  'subagents.cancelling': 'Cancelling…',

  'changes.title': '{count} files changed',
  'changes.undo': 'Undo',
  'changes.noBackup': 'No backup record for this path in this session',
  'changes.tooLarge': 'File too large; the net diff is not rendered in full',
  'changes.created': 'File created in this session (no net change yet)',
  'changes.noDiff': 'No difference from the backup baseline (possibly undone)',
  'changes.undone': 'Undone',
  'changes.undoTitle': 'Undo the last batch',
  'changes.undoConfirm': 'Confirm undo',
  'changes.undoPreviewPrefix': 'About to undo the last batch across ',
  'changes.undoPreviewSuffix': ' files:',
  'changes.warnModified':
    '{path}: modified externally since the backup; undoing may overwrite manual changes',
  'changes.warnMissing': '{path}: backup object missing; this file will be skipped',
  'changes.noUndoable': 'No undoable batch (no_backup).',

  'pair.deviceFallback': 'Device',
  'pair.subtitle':
    'Generate a pairing code on the desktop web console (Remote Control page), then scan or enter it here',
  'pair.pairing': 'Pairing…',
  'pair.codePlaceholder': '8-digit pairing code',
  'pair.pair': 'Pair',
  'pair.gatewayPlaceholder': 'Gateway URL (optional) https://…',
  'pair.gatewaySaved': 'Gateway URL saved',
  'pair.gatewayHint': 'Gateway: {label} (for standalone deployments, set the gateway URL first)',

  'welcome.subtitle': 'Remotely control your Volund desktop',
  'welcome.entering': 'Connected — entering…',
  'welcome.connecting': 'Connecting to gateway {host}…',
  'welcome.skip': 'Skip and enter anyway',

  'gateway.baseInvalid': 'Gateway address must start with http(s)://',
  'gateway.connectFailed':
    'Cannot reach the gateway: check the address; for cross-origin setups the gateway must allow this origin in GATEWAY_CORS_ORIGINS',
  'gateway.pairFailed': 'Pairing failed ({status})',
  'gateway.sessionExpired': 'Credentials expired, please pair again',
  'gateway.requestFailed': 'Gateway request failed ({status})',
  'gateway.uploadFailed': 'Image upload failed ({status})',
  'gateway.downloadFailed': 'Image download failed ({status})',
}

export const dictionaries: Record<'zh' | 'en', Record<DictKey, string>> = { zh, en }
